# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
                ('account_type', models.PositiveSmallIntegerField(choices=[(1, 'Checking'), (2, 'Savings')])),
                ('owner_full_name', models.CharField(max_length=300)),
                ('owner_birth_date', models.DateField()),
            ],
        ),
    ]
